### ISSUE TITLE
feat: support URNs

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/tripsu#50]
Currently, we assume that the prefix and fragment are separated by `#` or `/`,  however, in the case of URNs, the separator is `:`. This is problematic, because in regular URIs, `:` appears to be a valid character within fragment.

How do we generalize the splitting to support URNs? Any idea @rmfranken?

**Comment by rmfranken** [comment]
hmmm. So, a URN is a unique identifier - but it need not point to (resolvable or unresolvable location) like a URI does. I think that's where the rules for URN are slightly looser than with URI's. But even then - there is no guarantee that a slash or hashtag will separate a postfix from it's prefix. It's just a habit/best practice, but RDF does not care. You could also not use any separator, as I've done mistakenly in the past. You should not count on the separator being there from a legal RDF n-triples perspective. I would get rid of all things "prefix" and pseudonymize the whole URI every time (granted, this is computationally maybe more costly than prefixed URI's)

do you have some example of the problem? With the expected output vs. what tripsu is doing now? I'm not sure how the URN's are serialized in n-triples. I've never encountered that before, so this sounds like a fun new rabbit hole to explore.

**Comment by cmdoret** [comment]
Indeed, hashing the whole uri would be slower, plus retaining the domain is somewhat convenient. However, one could argue that there might be sensitive data in the prefix as well. We can do that.

In ntriples, urn are serialized as: `<urn:af1324cdd>`


Currently we basically do (pseudocode) `uri.split(['#', '/']).unwrap()`, where unwrap() means "it's never gonna fail, trust me, and if it does, crash everything". In any case, we should use `.expect("encountered uri with unexpected separator")` instead to at least inform the user of the issue.

**Comment by cmdoret** [comment]
Also, if we hash the whole URI, we need to write a new prefix; we could add an option to specify a base uri, but would probably need a default. This raises the question of what should be this default.

**Comment by cmdoret** [comment]
based on discussion with @rmfranken the solution described in #51 will be implemented instead
